# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 25
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: stockhero
  pool: 5
  username: dylanwright
  password: Rippy101

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: dylanwright
  password: Rippy101
