#this file is overwritten for production environment.

#default: &default
#  adapter: sqlite3
#  pool: 25
#  timeout: 5000

development:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: stockhero_development
  pool: 5
  username: seanmerrifield
  password: Vegitto1
  port: 5432

test:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: stockhero_test
  pool: 5
  username: seanmerrifield
  password: Vegitto1
  port: 5432
