# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:concurrency: 5 #maximum #of threads for 1 dyno = 256 threads. There are currently 1 workers, so 1*25 = 25 possible threads.
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:logfile: ./log/sidekiq.log
:timeout: 8
:pidfile: ./tmp/pids/sidekiq.pid
# :queues:
#  - [often, 7]
#  - [default, 5]
#  - [seldom, 3]